### ISSUE TITLE
Is there a way to get the url of the generated audio instead of the actual file

### ISSUE THREAD

**Issue by Dustinhoefer** [AndrewCPU/elevenlabs-api#11]
I want to be able to play the audio in a web application.
Thus, local access to files is not possible.

Is there currently any way to get the URL of the file to play?
Or does this have to be implemented first?

BTW: very nice api, working great so far! Thank you!

Kind regards
Dustin

**Comment by Andrewcpu** [comment]
Hi Dustin,

Thank you for your usage and question! You make a good point, I can add that functionality later today or tomorrow.. I'll update this issue when it's done.

**Comment by Andrewcpu** [comment]
@Dustinhoefer Ok, I understand why I didn't include it to start. 

The API response does not provide us with the link in response to the API call unfortunately. It provides the actual file as if it were a download. 

You'll most likely have to download the files and serve them from your own server. (Assuming they're not using their own API keys, they can't download audio generated from your API account without your API key which is a bad idea).

2 options:
1. Download the file on a server, and serve the audio files from your server. 
2. Give users your API key, find a way to get the history item for that generation, and use HistoryItem#getDownloadUrl() (I'm adding in  2.7.7)

**Comment by Dustinhoefer** [comment]
Thank you! Option two sounds like the one most usable for me and the program :)

Looking forward to version 2.7.7

**Comment by Andrewcpu** [comment]
Refresh your maven caches and check for 2.7.7.. I'll update the readme and will have to do another update shortly to fix speech-to-speech when they re-release it.

**Comment by Dustinhoefer** [comment]
Thank you so much, this works with my setup like a charm!

While I have you here, what exactly is "generateStream" used for?
Would I get faster generations there?

**Comment by Andrewcpu** [comment]
generateStream would only be helpful if you can redirect the InputStream to your user and play the inputstream on your users device out of a speaker (In your setup). But having them download a file works too. 

For example, for with generateStream it returns an InputStream which means you can route the playback audio directly to your speakers without needing to save and read the file.
