### ISSUE TITLE
IntelliJ CANNOT FIND Dependency

### ISSUE THREAD

**Issue by Br1anSimon** [AndrewCPU/elevenlabs-api#4]
Hello. I would like to admit a few things. Firstly, i am new to using maven. Secondly, I am very lost. I am trying to create a new maven project in intellij, and add the dependency for this api. In my pom.xml file, i have the following:
 `<dependency>
    <groupId>net.andrewcpu.elevenlabs</groupId>
    <artifactId>elevenlabs-api</artifactId>
    <version>1.0-SNAPSHOT</version>
</dependency>`.
I have also tried: 
`<dependency>
    <groupId>net.andrewcpu</groupId>
    <artifactId>elevenlabs-api</artifactId>
    <version>1.0-SNAPSHOT</version>
</dependency>`.

Neither of these update the maven dependencies. I have even tried using the search bar in IntelliJ to find the dependency, and nothing works. Whenever I open the terminal in IntelliJ and type in "mvn install" it says that the command was not found. I really want to use this to create an app, but i am getting very frustrated. If anyone could help me, that would be awesome. Thank you.

**Comment by Br1anSimon** [comment]
I have switched my jdk to java 17, and it found it. Now it is saying that it cannot resolve the dependency

**Comment by Andrewcpu** [comment]
Hi! @DiamondShadows Strange, yes another user recommended I lower the target sdk. I don't think it's your fault, I'll check on this in a couple days. I'm currently away.

**Comment by Andrewcpu** [comment]
I downgraded the repo JDK version to 11 and pushed a snapshot build of v2.0.. Let me know if it works for you:
<dependency>
  <groupId>net.andrewcpu</groupId>
  <artifactId>elevenlabs-api</artifactId>
  <version>2.0-SNAPSHOT</version>
</dependency>
