### ISSUE TITLE
Resources for elevenlabs-api are not found in the maven repository

### ISSUE THREAD

**Issue by FlickerMi** [AndrewCPU/elevenlabs-api#7]
not found: https://mvnrepository.com/search?q=net.andrewcpu%3Aelevenlabs-api

Importing jar packages locally will cause conflicts with springboot logback. It is hoped that you can upload them to maven repository. thanks

**Comment by Andrewcpu** [comment]
Hmm. Taking a look now.

**Comment by Andrewcpu** [comment]
It should be available now as:

`<dependency>
  <groupId>net.andrewcpu</groupId>
  <artifactId>elevenlabs-api</artifactId>
  <version>2.1</version>
</dependency>`

The mvnrepository engine may need a day to update. Let me know if you see it.

**Comment by FlickerMi** [comment]
Yes, I found it.

https://mvnrepository.com/artifact/net.andrewcpu/elevenlabs-api
